Repository hooligram/hooligram-client, pull requests merged in 2019-02, with the labels that each got.

#21 Feature/rename lib to app
  .flowconfig
  README.md
  android/app/src/main/res/values/strings.xml
  app.json
  app/hooligram-api/__tests__/hooligramApi.test.js
  app/hooligram-api/hooligramApi.js
  app/hooligram-api/index.js
  app/hooligram-api/package.json
  app/index.js
  app/navigation/index.js
  app/navigation/onboarding-stack.js
  app/navigation/package.json
  app/resources/images/background.png
  app/resources/package.json
  app/screens/Conversation/Conversation.js
  app/screens/Conversation/index.js
  app/screens/OnboardingAgree/OnboardingAgree.js
  app/screens/OnboardingAgree/index.js
  app/screens/OnboardingRequestCode/OnboardingRequestCode.js
  app/screens/OnboardingRequestCode/index.js
  app/screens/OnboardingRequestCode/presenter.js
  app/screens/index.js
  app/screens/package.json
  app/state/actions/api.js
  app/state/actions/forms.js
  app/state/middlewares/api/api.js
  app/state/middlewares/api/index.js
  app/state/package.json
  app/state/reducers/forms/__tests__/forms.test.js
  app/state/reducers/forms/forms.js
  app/state/reducers/forms/index.js
  app/state/reducers/index.js
  app/state/store/index.js
  app/state/store/store.js
  index.js
Labels: enhancement

#27 Feature/fix remote debugging error
  app/screens/OnboardingRequestCode/OnboardingRequestCode.js
  app/screens/OnboardingRequestCode/presenter.js
Labels: bug

#25 Feature/submit verification code
  README.md
  app/constants/Colors.js
  app/constants/index.js
  app/constants/package.json
  app/hooligram-api/__tests__/hooligramApi.test.js
  app/hooligram-api/hooligramApi.js
  app/index.js
  app/navigation/onboarding-stack.js
  app/screens/OnboardingAgree/OnboardingAgree.js
  app/screens/OnboardingAgree/__tests__/presenter.test.js
  app/screens/OnboardingAgree/index.js
  app/screens/OnboardingAgree/presenter.js
  app/screens/OnboardingInitialize/OnboardingInitialize.js
  app/screens/OnboardingInitialize/index.js
  app/screens/OnboardingRequestCode/OnboardingRequestCode.js
  app/screens/OnboardingRequestCode/__tests__/presenter.test.js
  app/screens/OnboardingRequestCode/presenter.js
  app/screens/OnboardingSubmitCode/OnboardingSubmitCode.js
  app/screens/OnboardingSubmitCode/__tests__/presenter.test.js
  app/screens/OnboardingSubmitCode/index.js
  app/screens/OnboardingSubmitCode/presenter.js
  app/screens/index.js
  app/state/actions/api.js
  app/state/actions/forms.js
  app/state/actions/profile.js
  app/state/middlewares/api/api.js
  app/state/middlewares/navigation/__tests__/navigation.test.js
  app/state/middlewares/navigation/index.js
  app/state/middlewares/navigation/navigation.js
  app/state/reducers/forms/__tests__/forms.test.js
  app/state/reducers/forms/forms.js
  app/state/reducers/index.js
  app/state/reducers/profile/__tests__/code-request.test.js
  app/state/reducers/profile/__tests__/verification.test.js
  app/state/reducers/profile/code-request.js
  app/state/reducers/profile/index.js
  app/state/reducers/profile/verification.js
  app/state/store/store.js
Labels: enhancement

#32 refactor/imran/clearer-action-types-naming
  app/hooligram-api/__tests__/hooligramApi.test.js
  app/hooligram-api/hooligramApi.js
  app/index.js
  app/state/actions/api.js
  app/state/actions/app.js
  app/state/actions/forms.js
  app/state/actions/websocket.js
  app/state/middlewares/api/__tests__/api.test.js
  app/state/middlewares/api/api.js
  app/state/middlewares/persistence/__tests__/persistence.test.js
  app/state/middlewares/persistence/persistence.js
  app/state/reducers/forms/__tests__/forms.test.js
  app/state/reducers/forms/forms.js
  package.json
  setup-jest.js
  yarn.lock
Labels: refactor

#38 refactor/migrate-to-react-native-config
  .babelrc
  android/app/build.gradle
  android/app/src/main/java/com/hooligram/MainApplication.java
  android/settings.gradle
  app/hooligram-api/index.js
  app/screens/Conversation/Conversation.js
  ios/hooligram.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: enhancement, refactor

#36 docs/connect-to-local-server
  README.md
  app/hooligram-api/__tests__/hooligramApi.test.js
  app/hooligram-api/hooligramApi.js
  app/state/actions/websocket.js
Labels: enhancement

#42 feature/onboarding-profile-info-screen
  app/navigation/onboarding-stack.js
  app/screens/Conversation/Conversation.js
  app/screens/OnboardingInitialize/OnboardingInitialize.js
  app/screens/OnboardingInitialize/index.js
  app/screens/OnboardingInitialize/presenter.js
  app/screens/OnboardingProfileInfo/OnboardingProfileInfo.js
  app/screens/OnboardingProfileInfo/index.js
  app/screens/OnboardingProfileInfo/presenter.js
  app/screens/index.js
  app/state/actions/forms.js
  app/state/actions/profile.js
  app/state/middlewares/navigation/__tests__/navigation.test.js
  app/state/middlewares/navigation/navigation.js
  app/state/middlewares/persistence/__tests__/persistence.test.js
  app/state/middlewares/persistence/persistence.js
  app/state/reducers/forms/__tests__/forms.test.js
  app/state/reducers/forms/forms.js
  app/state/reducers/profile/__tests__/code-request.test.js
  app/state/reducers/profile/__tests__/info.test.js
  app/state/reducers/profile/__tests__/verification.test.js
  app/state/reducers/profile/code-request.js
  app/state/reducers/profile/index.js
  app/state/reducers/profile/info.js
Labels: enhancement

#41 refactor: put action types in one place
  app/state/actions/app.js
  app/state/actions/forms.js
  app/state/actions/index.js
  app/state/actions/persistence.js
  app/state/actions/profile.js
  app/state/actions/websocket.js
  app/state/middlewares/api/__tests__/api.test.js
  app/state/middlewares/api/api.js
  app/state/middlewares/navigation/navigation.js
  app/state/middlewares/persistence/persistence.js
  app/state/reducers/forms/forms.js
  app/state/reducers/profile/code-request.js
  app/state/reducers/profile/info.js
  app/state/reducers/profile/verification.js
Labels: enhancement

#49 init .travis.yml
  .travis.yml
Labels: enhancement

#54 bugfix: should go to conversation
  app/persistence-api/__tests__/persistence-api.test.js
  app/screens/Conversation/Conversation.js
  app/state/middlewares/navigation/navigation.js
  app/state/middlewares/navigation/utils.js
  app/state/reducers/app/__tests__/app.test.js
  app/state/reducers/app/app.js
  app/state/reducers/app/index.js
  app/state/reducers/index.js
  index.js
Labels: bug

#55 Feature/authenticate navigate on app startup
  app/components/ActivityIndicator.js
  app/components/index.js
  app/navigation/index.js
  app/navigation/routeNames.js
  app/screens/OnboardingInitialize/OnboardingInitialize.js
  app/screens/Splash/Splash.js
  app/screens/Splash/index.js
  app/screens/Splash/presenter.js
  app/screens/index.js
  app/state/middlewares/navigation/navigation.js
Labels: enhancement

#59 Bugfix/fix messages persistence
  app/state/actions/app.js
  app/state/actions/index.js
  app/state/actions/profile.js
  app/state/middlewares/navigation/__tests__/navigation.test.js
  app/state/middlewares/navigation/navigation.js
  app/state/middlewares/persistence/__tests__/persistence.test.js
  app/state/middlewares/persistence/persistence.js
  app/state/reducers/app/__tests__/app.test.js
  app/state/reducers/app/app.js
  app/state/reducers/messages/messages.js
  app/state/reducers/profile/info.js
Labels: bug

#46 remove forms from redux
  README.md
  app/components/ActivityIndicator.js
  app/components/Message/Message.js
  app/components/MessageWriter/MessageWriter.js
  app/constants/country-codes.js
  app/constants/index.js
  app/constants/package.json
  app/navigation/conversation-stack.js
  app/navigation/onboarding-stack.js
  app/screens/Conversation/__tests__/presenter.test.js
  app/screens/Conversation/presenter.js
  app/screens/OnboardingAgree/OnboardingAgree.js
  app/screens/OnboardingAgree/presenter.js
  app/screens/OnboardingInitialize/OnboardingInitialize.js
  app/screens/OnboardingProfileInfo/OnboardingProfileInfo.js
  app/screens/OnboardingProfileInfo/presenter.js
  app/screens/OnboardingRequestCode/OnboardingRequestCode.js
  app/screens/OnboardingRequestCode/__tests__/presenter.test.js
  app/screens/OnboardingRequestCode/presenter.js
  app/screens/OnboardingSubmitCode/OnboardingSubmitCode.js
  app/screens/OnboardingSubmitCode/__tests__/presenter.test.js
  app/screens/OnboardingSubmitCode/presenter.js
  app/screens/Splash/index.js
  app/screens/package.json
  app/state/actions/authorization.js
  app/state/actions/profile.js
  app/state/middlewares/navigation/__tests__/navigation.test.js
  app/state/middlewares/navigation/navigation.js
  app/state/reducers/authorization/authorization.js
  app/state/reducers/forms/__tests__/forms.test.js
  app/state/reducers/forms/forms.js
  app/state/reducers/forms/index.js
  app/state/reducers/index.js
  app/state/reducers/profile/__tests__/code-request.test.js
  app/state/reducers/profile/__tests__/index.test.js
  app/state/reducers/profile/__tests__/info.test.js
  app/state/reducers/profile/__tests__/verification.test.js
  app/state/reducers/profile/code-request.js
  app/state/reducers/profile/index.js
  app/state/reducers/profile/info.js
  app/state/reducers/profile/verification.js
  app/state/selectors/__tests__/index.test.js
  app/state/selectors/index.js
  app/utils/format-phone-number.js
  app/utils/index.js
  app/utils/package.json
Labels: enhancement
